project:
  type: website
  output-dir: _site

website:
  title: "Sam Forbes"
  google-analytics: "G-NMRLY17Y6E"
  navbar:
    left:
      - text: Research and Essays
        menu:
          - text: Research
            href: research.qmd
          - text: Essays
            href: essays.qmd
      - text: Tutoring
        menu:
          - text: Overview
            href: tutoring.qmd
          - text: GCSE Maths
            href: gcse-maths.qmd

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css



