# project:
#   type: website
#   output-dir: _site

# website:
#   title: "Sam Forbes"
#   google-analytics: "G-NMRLY17Y6E"
#   navbar:
#     left:
#       - text: Research & Essays
#         menu:
#           - text: Research
#             href: research.qmd
#           - text: Essays
#             href: essays.qmd
#       - text: Resources
#         menu:
#           - text: Worksheets
#             href: Worksheets.qmd
#       - text: Interactive
#         href: Interactive_addition.html

# format:
#   html:
#     theme: cosmo
#     toc: false
#     css: styles.css
project:
  type: website
  output-dir: _site

website:
  title: "Sam Forbes"
  google-analytics: "G-NMRLY17Y6E"
  navbar:
    left:
      - text: "Research & Essays"
        menu:
          - text: "Research"
            href: research.qmd
          - text: "Essays"
            href: essays.qmd
      - text: "Resources"
        menu:
          - text: "Worksheets"
            href: Worksheets.qmd
          - text: "Interactive"
            href: Interactive.qmd

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css



