## GCSE Foundation Worksheets
**Note these worksheets have been generated at pace with the help of Gemini and are in the process of being checked by me! The majority of questions are fine but some are not!**

### Number, Ratio & Algebra

| Topic  | Subtopic | Download |
| :--- | :--- | :--- |
| **Non-Calculator Arithmetic** | Negative Numbers | [PDF (Questions & Solutions)](gcse_maths_files/negative_numbers.pdf) |
| | Whole Number Arithmetic | [PDF (Questions & Solutions)](gcse_maths_files/whole_number_arithmetic.pdf) |
| | Decimal Arithmetic | [PDF (Questions & Solutions)](gcse_maths_files/decimals.pdf) |
| | Order of Operations | [PDF (Questions & Solutions)](gcse_maths_files/order_operations.pdf) |
| | Non-Calculator Arithmetic Mix | [PDF (Questions & Solutions)](gcse_maths_files/non_calc_arith_mix.pdf) |
| **Approximations** | Rounding to Decimal Places | [PDF (Questions & Solutions)](gcse_maths_files/rounding_decimal_places.pdf) |
| | Rounding to Significant Figures | [PDF (Questions & Solutions)](gcse_maths_files/significant_figures.pdf) |
| | Estimation | [PDF (Questions & Solutions)](gcse_maths_files/estimation.pdf) |
| | Rounding Errors & Bounds | [PDF (Questions & Solutions)](gcse_maths_files/rounding_errors.pdf) |
|**Powers & Roots** | Squares, Cubes & Roots | [PDF (Questions & Solutions)](gcse_maths_files/squares_cubes_roots.pdf) |
| | Index Laws | [PDF (Questions & Solutions)](gcse_maths_files/indices.pdf) |
| | Standard Form | [PDF (Questions & Solutions)](gcse_maths_files/standard_form.pdf) |
|**Multiples & Factors** | Finding Multiples & Factors | [PDF (Questions & Solutions)](gcse_maths_files/finding_multiples_factors.pdf) |
| | Prime Numbers | [PDF (Questions & Solutions)](gcse_maths_files/prime_numbers.pdf) |
| | LCM & HCF| [PDF (Questions & Solutions)](gcse_maths_files/LCM_and_HCF.pdf) |
|**Fractions** | Equivalent Fractions | [PDF (Questions & Solutions)](gcse_maths_files/equivalent_fractions.pdf) |
| | Mixed Numbers | [PDF (Questions & Solutions)](gcse_maths_files/mixed_numbers.pdf) |
| | Ordering Fractions | [PDF (Questions & Solutions)](gcse_maths_files/ordering_fractions.pdf) |
| | Adding & Subtracting Fractions | [PDF (Questions & Solutions)](gcse_maths_files/adding_subtracting_fractions.pdf) |
| | Multiplying & Dividing Fractions | [PDF (Questions & Solutions)](gcse_maths_files/multiplying_dividing_fractions.pdf) |
| | Fractions & Decimals | [PDF (Questions & Solutions)](gcse_maths_files/fractions_and_decimals.pdf) |
| | Fractions Problems | [PDF (Questions & Solutions)](gcse_maths_files/fractions_problems.pdf) |
|**Ratios** | Ratios & Simplifying | [PDF (Questions & Solutions)](gcse_maths_files/ratios_and_simplifying.pdf) |
| | Using Ratios | [PDF (Questions & Solutions)](gcse_maths_files/using_ratios.pdf) |
| | Dividing in a Given Ratio | [PDF (Questions & Solutions)](gcse_maths_files/dividing_in_a_given_ratio.pdf) |
| | Ratio Problems | [PDF (Questions & Solutions)](gcse_maths_files/ratio_problems.pdf) |
|**Percentages** | Percentages | [PDF (Questions & Solutions)](gcse_maths_files/percentages.pdf) |
| | Percentages, Fractions & Decimals| [PDF (Questions & Solutions)](gcse_maths_files/percentages_fractions_decimals.pdf) |
| | Percentage Increase & Decrease| [PDF (Questions & Solutions)](gcse_maths_files/percentage_increase_decrease.pdf) |
| | Compound Growth & Decay| [PDF (Questions & Solutions)](gcse_maths_files/compound_growth_decay.pdf) |
| | Percentages Problems| [PDF (Questions & Solutions)](gcse_maths_files/percentages_problems.pdf) |
|**Algebraic Expressions** | Collecting Like Terms | [PDF (Questions & Solutions)](gcse_maths_files/collecting_like_terms.pdf) |
|| Expanding Brackets | [PDF (Questions & Solutions)](gcse_maths_files/expanding_brackets.pdf) |
|| Factorising | [PDF (Questions & Solutions)](gcse_maths_files/factorising.pdf) |
| **Equations & Inequalities** | Solving Equations | [PDF (Questions & Solutions)](gcse_maths_files/solving_equations.pdf) |
| | Solving Harder Equations | [PDF (Questions & Solutions)](gcse_maths_files/solving_harder_equations.pdf) |
| | Writing Equations | [PDF (Questions & Solutions)](gcse_maths_files/writing_your_own_equations.pdf) |
| | Solving Inequalities | [PDF (Questions & Solutions)](gcse_maths_files/solving_inequalities.pdf) |
| | Simultaneous Equations | [PDF (Questions & Solutions)](gcse_maths_files/simultaneous_equations.pdf) |
| | Solving Quadratic Equations | [PDF (Questions & Solutions)](gcse_maths_files/solving_quadratic_equations.pdf) |
| | Equations & Inequalities Problems | [PDF (Questions & Solutions)](gcse_maths_files/equations_and_inequalities_problems.pdf) |
| **Formulas & Functions** | Writing Formulas | [PDF (Questions & Solutions)](gcse_maths_files/writing_formulas.pdf) |
| | Substituting into a Formula | [PDF (Questions & Solutions)](gcse_maths_files/substituting_into_formulas.pdf) |
| | Rearranging Formulas | [PDF (Questions & Solutions)](gcse_maths_files/rearranging_formulas.pdf) |
| | Functions | [PDF (Questions & Solutions)](gcse_maths_files/functions.pdf) |
| | Formulas & Functions Problems | [PDF (Questions & Solutions)](gcse_maths_files/formulas_and_functions_problems.pdf) |
| **Sequences** | Term-to-Term Rules | [PDF (Questions & Solutions)](gcse_maths_files/sequences_term-to-term_rules.pdf) |
| | Position-to-Term Rules | [PDF (Questions & Solutions)](gcse_maths_files/sequences_position-to-term_rules.pdf) |
| | Finding Position-to-Term Rules | [PDF (Questions & Solutions)](gcse_maths_files/finding_a_position-to-term_rule.pdf) |
| **Graphs & Equations** | Coordinates | [PDF (Questions & Solutions)](gcse_maths_files/coordinates.pdf) |
| | Horizontal & Vertical Graphs | [PDF (Questions & Solutions)](gcse_maths_files/horizontal_and_vertical_graphs.pdf) |
| | Other Straight-Line Graphs | [PDF (Questions & Solutions)](gcse_maths_files/other_straight-line_graphs.pdf) |
| | Gradients | [PDF (Questions & Solutions)](gcse_maths_files/gradients.pdf) |
| | Equations of Straight-Line Graphs | [PDF (Questions & Solutions)](gcse_maths_files/equations_of_straight-line_graphs.pdf) |
| | Quadratic Graphs | [PDF (Questions & Solutions)](gcse_maths_files/quadratic_graphs.pdf) |
| | Harder Graphs | [PDF (Questions & Solutions)](gcse_maths_files/harder_graphs.pdf) |
| | Graphs & Equations Problems | [PDF (Questions & Solutions)](gcse_maths_files/graphs_and_equations_problems.pdf) |
| **Real-Life Graphs** | Interpreting Real-Life Graphs | [PDF (Questions & Solutions)](gcse_maths_files/interpreting_real-life_graphs.pdf) |
| | Drawing Real-Life Graphs | [PDF (Questions & Solutions)](gcse_maths_files/drawing_real-life_graphs.pdf) |
| **Proportion** | Direct Proportion | [PDF (Questions & Solutions)](gcse_maths_files/direct_proportion.pdf) |
| | Inverse Proportion | [PDF (Questions & Solutions)](gcse_maths_files/inverse_proportion.pdf) |
| | Proportion Problems | [PDF (Questions & Solutions)](gcse_maths_files/proportion_problems.pdf) |

### Geometry & Measures

| Topic | Subtopic | Download |
| :--- | :--- | :--- |
| **Angles & 2D Shapes** | Basic Angle Properties | [PDF (Questions & Solutions)](gcse_maths_files/basic_angle_properties.pdf) |
| | Triangles | [PDF (Questions & Solutions)](gcse_maths_files/triangles.pdf) |
| | Parallel & Intersecting Lines | [PDF (Questions & Solutions)](gcse_maths_files/parallel_and_intersecting_lines.pdf) |
| | Quadrilaterals | [PDF (Questions & Solutions)](gcse_maths_files/quadrilaterals.pdf) |
| | Interior & Exterior Angles | [PDF (Questions & Solutions)](gcse_maths_files/interior_and_exterior_angles.pdf) |
| | Symmetry | [PDF (Questions & Solutions)](gcse_maths_files/symmetry.pdf) |
| | Angles & 2D Shapes Problems | [PDF (Questions & Solutions)](gcse_maths_files/angles_and_2d_shapes_problems.pdf) |
| **Units, Measuring & Estimating** | Reading Scales | [PDF (Questions & Solutions)](gcse_maths_files/reading_scales.pdf) |
| | Converting Metric Units | [PDF (Questions & Solutions)](gcse_maths_files/converting_metric_units_length_mass_and_volume.pdf) |
| | Converting Units (Area & Volume) | [PDF (Questions & Solutions)](gcse_maths_files/converting_units_area_and_volume.pdf) |
| | Metric & Imperial Units | [PDF (Questions & Solutions)](gcse_maths_files/metric_and_imperial_units.pdf) |
| | Estimating in Real Life | [PDF (Questions & Solutions)](gcse_maths_files/estimating_in_real_life.pdf) |
| **Speed, Density & Pressure** | Speed, Distance & Time | [PDF (Questions & Solutions)](gcse_maths_files/speed_distance_time_calculations.pdf) |
| | Density, Mass & Volume | [PDF (Questions & Solutions)](gcse_maths_files/density_mass_volume_calculations.pdf) |
| | Pressure, Force & Area | [PDF (Questions & Solutions)](gcse_maths_files/pressure_force_area_calculations.pdf) |
| | Distance-Time Graphs | [PDF (Questions & Solutions)](gcse_maths_files/distance-time_graphs.pdf) |
| **Scale Drawings & Bearings** | Scale Drawings | [PDF (Questions & Solutions)](gcse_maths_files/scale_drawings.pdf) |
| | Bearings | [PDF (Questions & Solutions)](gcse_maths_files/bearings.pdf) |
| | Scale Drawings & Bearings Problems | [PDF (Questions & Solutions)](gcse_maths_files/scale_drawings_and_bearings_problems.pdf) |
| **Pythagoras & Trigonometry** | Pythagoras' Theorem | [PDF (Questions & Solutions)](gcse_maths_files/pythagoras_theorem.pdf) |
| | Trigonometry (Sin, Cos & Tan) | [PDF (Questions & Solutions)](gcse_maths_files/trigonometry_sin_cos_and_tan.pdf) |
| | Pythagoras & Trigonometry Problems | [PDF (Questions & Solutions)](gcse_maths_files/pythagoras_and_trigonometry_problems.pdf) |
| **Vectors** | Column Vectors | [PDF (Questions & Solutions)](gcse_maths_files/column_vectors.pdf) |
| | Vectors Problems | [PDF (Questions & Solutions)](gcse_maths_files/vectors_problems.pdf) |
| **Constructions** | Circles | [PDF (Questions & Solutions)](gcse_maths_files/circles.pdf) |
| | Lines, Angles & Triangles | [PDF (Questions & Solutions)](gcse_maths_files/lines_angles_and_triangles.pdf) |
| | Constructions | [PDF (Questions & Solutions)](gcse_maths_files/constructions.pdf) |
| | Loci | [PDF (Questions & Solutions)](gcse_maths_files/loci.pdf) |
| **Area & Perimeter** | Rectangles & Triangles | [PDF (Questions & Solutions)](gcse_maths_files/rectangles_and_triangles.pdf) |
| | Other Quadrilaterals | [PDF (Questions & Solutions)](gcse_maths_files/other_quadrilaterals.pdf) |
| | Circumference of a Circle | [PDF (Questions & Solutions)](gcse_maths_files/circumference_of_a_circle.pdf) |
| | Area of a Circle | [PDF (Questions & Solutions)](gcse_maths_files/area_of_a_circle.pdf) |
| | Arcs & Sectors of Circles | [PDF (Questions & Solutions)](gcse_maths_files/arcs_and_sectors_of_circles.pdf) |
| | Area & Perimeter Problems | [PDF (Questions & Solutions)](gcse_maths_files/area_and_perimeter_problems.pdf) |
| **3D Shapes** | Nets | [PDF (Questions & Solutions)](gcse_maths_files/nets.pdf) |
| | Plans & Elevations | [PDF (Questions & Solutions)](gcse_maths_files/plans_and_elevations.pdf) |
| | Isometric Drawings | [PDF (Questions & Solutions)](gcse_maths_files/isometric_drawings.pdf) |
| | Volume | [PDF (Questions & Solutions)](gcse_maths_files/volume.pdf) |
| | Surface Area | [PDF (Questions & Solutions)](gcse_maths_files/surface_area.pdf) |
| | 3D Shapes Problems | [PDF (Questions & Solutions)](gcse_maths_files/3d_shapes_problems.pdf) |
| **Transformations** | Reflection | [PDF (Questions & Solutions)](gcse_maths_files/reflection.pdf) |
| | Rotation | [PDF (Questions & Solutions)](gcse_maths_files/rotation.pdf) |
| | Translations | [PDF (Questions & Solutions)](gcse_maths_files/translations.pdf) |
| | Enlargements | [PDF (Questions & Solutions)](gcse_maths_files/enlargements.pdf) |
| | Combinations of Transformations | [PDF (Questions & Solutions)](gcse_maths_files/combinations_of_transformations.pdf) |
| | Congruence & Similarity | [PDF (Questions & Solutions)](gcse_maths_files/congruence_and_similarity.pdf) |

### Statistics & Probability

| Topic | Subtopic | Download |
| :--- | :--- | :--- |
| **Collecting Data** | Types of Data | [PDF (Questions & Solutions)](gcse_maths_files/using_different_types_of_data.pdf) |
| | Data Collection & Questionnaires | [PDF (Questions & Solutions)](gcse_maths_files/data-collection_sheets_and_questionnaires.pdf) |
| | Sampling & Bias | [PDF (Questions & Solutions)](gcse_maths_files/sampling_and_bias.pdf) |
| **Analysing Data** | Using Lists & Tables | [PDF (Questions & Solutions)](gcse_maths_files/using_lists_and_tables.pdf) |
| | Averages & Range | [PDF (Questions & Solutions)](gcse_maths_files/averages_and_range.pdf) |
| | Two-Way Tables | [PDF (Questions & Solutions)](gcse_maths_files/two-way_tables.pdf) |
| | Bar Charts & Pictograms | [PDF (Questions & Solutions)](gcse_maths_files/bar_charts_and_pictograms.pdf) |
| | Stem & Leaf Diagrams | [PDF (Questions & Solutions)](gcse_maths_files/stem_and_leaf_diagrams.pdf) |
| | Pie Charts | [PDF (Questions & Solutions)](gcse_maths_files/pie_charts.pdf) |
| | Time Series | [PDF (Questions & Solutions)](gcse_maths_files/time_series.pdf) |
| | Scatter Graphs | [PDF (Questions & Solutions)](gcse_maths_files/scatter_graphs.pdf) |
| **Probability** | Probability Basics | [PDF (Questions & Solutions)](gcse_maths_files/probability_the_basics.pdf) |
| | Calculating Probabilities | [PDF (Questions & Solutions)](gcse_maths_files/calculating_probabilities.pdf) |
| | Listing Outcomes | [PDF (Questions & Solutions)](gcse_maths_files/listing_outcomes.pdf) |
| | Experimental Probability | [PDF (Questions & Solutions)](gcse_maths_files/probability_from_experiments.pdf) |
| | AND / OR Rules | [PDF (Questions & Solutions)](gcse_maths_files/the_and_or_rules.pdf) |
| | Tree Diagrams | [PDF (Questions & Solutions)](gcse_maths_files/tree_diagrams.pdf) |
| | Sets & Venn Diagrams | [PDF (Questions & Solutions)](gcse_maths_files/sets_and_venn_diagrams.pdf) | 